development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || ENV['STACKHERO_REDIS_URL_TLS'] || "redis://localhost:6379/1" %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['STACKHERO_REDIS_URL_TLS'] %>
  channel_prefix: granny_production
